server:
    port: 8081

spring:
    application:
        name: kafka-producer-service
    kafka:
        bootstrap-servers: ${KAFAK_BOOTSTRAP_SERVERS:localhost:9092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
    kafka:
        topic:
            orders-events: ${ORDERS_TOPIC_NAME:orders-events}

management:
    endpoints:
        web:
            exposure:
                include: health, info
    endpoint:
        health:
            show-details: always

logging:
    level:
        com.kafkalearning: INFO
        com.springframework.kafka: WARN
